version: '2'

services:

  web:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile_prod
    hostname: web.prod.local
    network_mode: host
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/nebular-angular-seed.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    container_name: nebular-angular-seed-prod
    image: nebular-angular-seed/prod
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    ports:
      - '4200:4200'
