FROM node:12.16.0 AS builder
WORKDIR /home/node/solicitudes-mantenimiento-web
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build.prod

FROM nginx:1.13
COPY --from=builder /home/node/solicitudes-mantenimiento-web/dist/solicitudes-mantenimiento-web /var/www/dist/solicitudes-mantenimiento-web
COPY ./.docker/nginx.conf /etc/nginx/conf.d/solicitudes-mantenimiento-web.template
